apiVersion: v1
kind: Service
metadata:
  name: fusion-auth-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: fusionauth-customer-os
    app.kubernetes.io/name: fusionauth
  ports:
    - name: http
      port: 9011
      targetPort: 9011
